[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
libs = ["node_modules", "lib"]
remappings = ["@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"]
fs_permissions = [{ access = "read", path = "./config" }, { access = "read", path = "./test/fixtures" }]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 128
depth = 64
fail_on_revert = false
