import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {ZeroHash} from 'ethers';
import {reconcile} from '../chain.js';
import {Journal,hash,stringify} from '../journal.js';
import {readPruningPolicy,validateCalculatorConfigShape} from '../config.js';
import {verifyPayoutHistory} from '../../keeper/verify-history.js';
import {historyFixture,holderA,holderB} from './helpers/history-fixture.js';

function rewriteHistory(dir,mutate) {
 const rows=new Journal(dir).entries();mutate(rows);let previous=null;
 for(const [index,row]of rows.entries()) {
  row.previous=previous;row.hash=hash({previous,record:row.record});previous=row.hash;
  fs.writeFileSync(path.join(dir,'periods',`${String(index+1).padStart(8,'0')}.json`),stringify(row));
 }
}
const root='0x'+'12'.repeat(32);
const samplePlan={roundId:'1',root,total:'10',payouts:{[holderA]:'10'},toBlock:90};
const sampleState=()=>({highestPrunedRoundId:'0',accrued:{},plans:{1:structuredClone(samplePlan)}});
const options={pruneSettledPlans:true};

test('pruning is a strict optional final config key requiring finalized history',async t=>{
 const f=await historyFixture(t);
 validateCalculatorConfigShape(f.config);
 validateCalculatorConfigShape({...f.config,pruneSettledPlans:true});
 assert.equal(readPruningPolicy(f.config),false);
 assert.equal(readPruningPolicy({...f.config,pruneSettledPlans:false}),false);
 for(const value of ['true','false',1,0,null])assert.throws(()=>readPruningPolicy({...f.config,pruneSettledPlans:value}),/must be a boolean/);
 assert.throws(()=>readPruningPolicy({...f.config,pruneSettledPlans:true,finalityTag:'safe'}),/requires finalized/);
 assert.throws(()=>validateCalculatorConfigShape({pruneSettledPlans:true,...f.config}),/in that order/);
 assert.throws(()=>validateCalculatorConfigShape({...f.config,unknown:true}),/in that order/);
});

test('omitting pruning preserves legacy journal bytes from the reviewed baseline',async t=>{
 const f=await historyFixture(t);for(let i=0;i<4;i++)await f.advance();
 // Generated by the exact calculator/{engine,chain,journal,core}.js at
 // 7c7e39f55453991bd89a3fd461a14b4e88c44c97 with this deterministic archive fixture.
 assert.deepEqual(new Journal(f.dir).entries().map(row=>row.hash),[
  '4b6cf65913707f68e1712f719ab965e7f09caf1d9f3fc8859aa178d79bcd46a9',
  '8779ca81cac52e8f73e2a07e9b4f19cbf92215531e51f8b651c8cf5b7ae04abb',
  'd883f9f377a1564d9d945e56f92b8ad313fd8888a410a64489c314d293d80191',
  '18ea8d7315b18266faa90aa52b1fd4fb6c22ac612306d884c9298faf2954382c',
  '8ea943091e9005fd938802f4e6a71ea133b7ccd8e743ca87b8e39ed75f685368',
 ]);
});

test('pruning deletes only freshly reconciled paid, partially paid, cancelled or superseded plans',async()=>{
 for(const kind of ['paid','partial','cancelled','foreign']) {
  const state=sampleState();
  if(kind==='partial'){state.plans[1].total='15';state.plans[1].payouts[holderB]='5';}
  const foreign='0x'+'f0'.repeat(32),distributed=kind==='paid'||kind==='partial'?10n:0n;
  const distributor={roundInfo:async(_id,{blockTag})=>{assert.equal(blockTag,100);return [kind==='foreign'?foreign:root,BigInt(state.plans[1].total),distributed,false,true];},
   filters:{Paid:()=>1},queryFilter:async()=>distributed?[{blockNumber:99,args:{account:holderA,amount:10n}}]:[]};
  const result=await reconcile(distributor,state,100,2000,options);
  assert.deepEqual(state.plans,{});assert.equal(state.highestPrunedRoundId,'1');
  assert.deepEqual(result.prunedRounds,[{roundId:'1',root,settledAt:100,superseded:kind==='foreign',...(kind==='foreign'?{foreignRoot:foreign}:{})}]);
  assert.deepEqual(state.accrued,kind==='partial'?{[holderB]:5n}:kind==='paid'?{}:{[holderA]:10n});
  const before=structuredClone(state);
  await reconcile({roundInfo:async()=>{throw Error('pruned round must not be recredited again');}},state,101,2000,options);
  assert.deepEqual(state,before);
 }
});

test('unproposed, pending and active plans remain retained with unchanged accounting',async()=>{
 for(const kind of ['unproposed','pending','active']) {
  const state=sampleState(),before=structuredClone(state);
  const d={roundInfo:async()=>kind==='active'?[root,10n,0n,true,false]:[ZeroHash,0n,0n,false,false],pending:async()=>kind==='pending'?[root,10n,123n]:[ZeroHash,0n,0n]};
  const result=await reconcile(d,state,100,2000,options);
  assert.equal(result.localReserved,kind==='unproposed'?10n:0n);assert.deepEqual(result.prunedRounds,[]);assert.deepEqual(state,before);
 }
});

test('pruning failures leave plans, recredits and scalar unchanged after prior successful reads',async()=>{
 for(const fault of ['missing','amount','duplicate','unknown','out-of-range','rpc']) {
  const state=sampleState();state.plans[2]={...structuredClone(samplePlan),roundId:'2'};const before=structuredClone(state);
  const d={roundInfo:async()=>[root,10n,10n,false,true],filters:{Paid:id=>id},queryFilter:async(id)=>{
   const valid={blockNumber:99,args:{account:holderA,amount:10n}};
   if(id==='1')return [valid];
   if(fault==='rpc')throw Error('archive unavailable');
   if(fault==='missing')return [];
   if(fault==='duplicate')return [valid,valid];
   if(fault==='amount')valid.args.amount=9n;
   if(fault==='unknown')valid.args.account=holderB;
   if(fault==='out-of-range')valid.blockNumber=101;
   return [valid];
  }};
  await assert.rejects(reconcile(d,state,100,2000,options),/payment|snapshot|archive/);
  assert.deepEqual(state,before,fault);
 }
});

test('pruning refuses malformed cursors, round keys and unverified settled flags',async()=>{
 for(const cursor of [undefined,1,-1,'-1','01','1.0',(1n<<256n).toString()]) {
  const state=sampleState();state.highestPrunedRoundId=cursor;
  const before=structuredClone(state);await assert.rejects(reconcile({},state,100,2000,options),/uint256/);assert.deepEqual(state,before);
 }
 const settled=sampleState();settled.plans[1].settled=true;
 await assert.rejects(reconcile({},settled,100,2000,options),/already-settled/);
 const key=sampleState();key.plans[1].roundId='2';
 await assert.rejects(reconcile({},key,100,2000,options),/plan key differs/);
});

test('a fresh pruning journal retains one live plan while immutable history independently replays',async t=>{
 const f=await historyFixture(t,{pruneSettledPlans:true});
 await f.advance();const original=fs.readFileSync(path.join(f.dir,'periods','00000002.json'));
 for(let i=0;i<31;i++)await f.advance();
 const rows=new Journal(f.dir).entries();
 assert.equal(rows.length,33);assert.equal(rows.filter(row=>row.record.plan).length,32);
 assert.ok(rows.every(({record})=>Object.keys(record.state.plans).length<=1));
 assert.equal(rows.at(-1).record.state.highestPrunedRoundId,'31');
 assert.deepEqual(fs.readFileSync(path.join(f.dir,'periods','00000002.json')),original);
 assert.equal((await verifyPayoutHistory({...f,rows})).periods,33);
 const retained=await historyFixture(t);
 for(let i=0;i<32;i++)await retained.advance();
 const legacyRows=new Journal(retained.dir).entries();
 assert.equal(legacyRows.at(-1).record.state.plans['1'].settled,true);
 assert.equal(Object.keys(legacyRows.at(-1).record.state.plans).length,32);
 const nested=records=>records.reduce((n,{record})=>n+Object.keys(record.state.plans).length,0);
 assert.equal(nested(rows),32);assert.equal(nested(legacyRows),528);
 t.diagnostic('32 plans: retained nested plan copies are 32 with pruning versus 528 without; this is a small synthetic fixture, not a production hosting estimate');
});

test('configuration changes cannot migrate an existing journal into or out of pruning',async t=>{
 for(const starting of [undefined,true]) {
  const f=await historyFixture(t,{pruneSettledPlans:starting});await f.advance();
  f.config.pruneSettledPlans=starting===true?false:true;
  await assert.rejects(f.advance(),/configuration changed/);
  assert.equal(new Journal(f.dir).entries().length,2);
 }
});

test('nextRoundId cannot reuse an ID whose full plan was pruned',async t=>{
 const f=await historyFixture(t,{pruneSettledPlans:true});await f.advance();await f.advance();
 const saved=fs.readFileSync(path.join(f.dir,'state.json'));
 f.distributor.nextRoundId=async()=>1n;
 await assert.rejects(f.advance(),/reuses a previously pruned round/);
 assert.deepEqual(fs.readFileSync(path.join(f.dir,'state.json')),saved);assert.equal(new Journal(f.dir).entries().length,3);
});

test('rehashing cannot conceal forged pruning cursors, removals or retained state',async t=>{
 for(const fault of ['cursor-type','cursor-overflow','cursor-forged','missing-summary','duplicate','retained-drop','settlement-block']) {
  const f=await historyFixture(t,{pruneSettledPlans:true});await f.advance();await f.advance();
  rewriteHistory(f.dir,rows=>{
   const record=rows[2].record;
   if(fault==='cursor-type')record.state.highestPrunedRoundId=1;
   if(fault==='cursor-overflow')record.state.highestPrunedRoundId=(1n<<256n).toString();
   if(fault==='cursor-forged')record.state.highestPrunedRoundId='99';
   if(fault==='missing-summary')record.prunedRounds=[];
   if(fault==='duplicate')record.prunedRounds.push({...record.prunedRounds[0]});
   if(fault==='retained-drop')record.state.plans={};
   if(fault==='settlement-block')record.prunedRounds[0].settledAt--;
  });
  assert.throws(()=>new Journal(f.dir).entries(),/uint256|removals|prior retained|retained plans|settlement identity/,fault);
 }
});

test('an internally consistent false settlement claim fails independent replay',async t=>{
 const f=await historyFixture(t,{pruneSettledPlans:true});await f.advance();await f.advance();
 rewriteHistory(f.dir,rows=>{const summary=rows[2].record.prunedRounds[0];summary.superseded=true;summary.foreignRoot='0x'+'f0'.repeat(32);});
 const rows=new Journal(f.dir).entries();
 await assert.rejects(verifyPayoutHistory({...f,rows}),/independent payout calculation mismatch/);
});

test('missing archive payments cannot commit a pruning period or delete persistent plans',async t=>{
 const f=await historyFixture(t,{pruneSettledPlans:true});await f.advance();
 const saved=fs.readFileSync(path.join(f.dir,'state.json'));
 f.distributor.queryFilter=async()=>[];
 await assert.rejects(f.advance(),/payment total mismatch/);
 assert.deepEqual(fs.readFileSync(path.join(f.dir,'state.json')),saved);assert.equal(new Journal(f.dir).entries().length,2);
});
